version: '3'
services:
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: wortox
      RABBITMQ_DEFAULT_PASS: wortox_password
    ports:
      - "5672:5672"
      - "15672:15672"